[package]
name = "entyties"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
actix-ws = "0.3.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3.31"
thiserror = "2.0.11"
